{% set name = "apache-airflow-providers-google" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-google-{{ version }}.tar.gz
  sha256: db7ed139a2e7750918c7cdf798292dd1e4c40b7e244d3d797edd95f4290e611f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - google-ads >=12.0.0
    - google-api-core >=1.25.1,<2.0.0
    - google-api-python-client >=1.6.0,<2.0.0
    - google-auth >=1.0.0,<2.0.0
    - google-auth-httplib2 >=0.0.1
    - google-cloud-automl >=2.1.0,<3.0.0
    - google-cloud-bigquery-datatransfer >=3.0.0,<4.0.0
    - google-cloud-bigtable >=1.0.0,<2.0.0
    - google-cloud-container >=0.1.1,<2.0.0
    - google-cloud-datacatalog >=3.0.0,<4.0.0
    - google-cloud-dataproc >=2.2.0,<3.0.0
    - google-cloud-dlp >=0.11.0,<2.0.0
    - google-cloud-kms >=2.0.0,<3.0.0
    - google-cloud-language >=1.1.1,<2.0.0
    - google-cloud-logging >=2.1.1,<3.0.0
    - google-cloud-memcache >=0.2.0,<1.1.0
    - google-cloud-monitoring >=2.0.0,<3.0.0
    - google-cloud-os-login >=2.0.0,<3.0.0
    - google-cloud-pubsub >=2.0.0,<3.0.0
    - google-cloud-redis >=2.0.0,<3.0.0
    - google-cloud-secret-manager >=0.2.0,<2.0.0
    - google-cloud-spanner >=1.10.0,<2.0.0
    - google-cloud-speech >=0.36.3,<2.0.0
    - google-cloud-storage >=1.30,<2.0.0
    - google-cloud-tasks >=2.0.0,<3.0.0
    - google-cloud-texttospeech >=0.4.0,<2.0.0
    - google-cloud-translate >=1.5.0,<2.0.0
    - google-cloud-videointelligence >=1.7.0,<2.0.0
    - google-cloud-vision >=0.35.2,<2.0.0
    - google-cloud-workflows >=0.1.0,<2.0.0
    - grpcio-gcp >=0.2.2
    - httpx
    - json-merge-patch >=0.2,<0.3
    - pandas-gbq <0.15.0

test:
  imports:
    - airflow.providers.google
    - airflow.providers.google.ads
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Google services for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
